### PR TITLE
bug_5549 - [Wdrożenie] [Python] Nowy ekran - timeline

### PR DESCRIPTION
**Pull request by filipgorczynski**
https://gist.github.com/filipgorczynski/fb89dc1d94d866a3b674

### CODE REVIEW

**Comment by filipgorczynski** [comment]
Bug_5549: [Wdrożenie] [Python] Nowy ekran - timeline: poprawki związane z Pull Request.
https://gist.github.com/filipgorczynski/3208e7cb08d98eddb588

**Comment by filipgorczynski** [comment]
bug_5549 Pull Request fixes: alphabetically imports sorting; changes embedded list into dictionary.
https://gist.github.com/filipgorczynski/c611b293de8ad5370121

**Comment by filipgorczynski** [comment]
bug_5549 - nested list fixes.
https://gist.github.com/filipgorczynski/3d8c7c19aa570ca634b1

**Comment by rszalski** [comment]
That's  better! :ok_hand:

**Pull request merged**
